import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f5f7fb',
  },
  container: {
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 12,
  },
  appBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // paddingHorizontal: 20,
    paddingVertical: 5,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eef2ff',
    backgroundColor: '#e5e8ed',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#eef2ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    color: '#4f46e5',
    fontSize: 20,
    fontWeight: '700',
  },
  appBarTitleWrap: {
    flex: 1,
    alignItems: 'center',
  },
  appBarTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '700',
  },
  appBarSubtitle: {
    color: '#6b7280',
    fontSize: 12,
    marginTop: 2,
  },
  appBarSpacer: {
    width: 40,
    height: 40,
  },
  greeting: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  subtitle: {
    fontSize: 13,
    color: '#6b7280',
    marginTop: 4,
  },
  addButton: {
    backgroundColor: '#4f46e5',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  balanceCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderRadius: 24,
    backgroundColor: '#111827',
    marginBottom: 16,
  },
  balanceInfo: {
    flex: 1,
  },
  balanceLabel: {
    color: '#9ca3af',
    fontSize: 13,
    marginBottom: 8,
  },
  balanceAmount: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 6,
  },
  balanceTrend: {
    color: '#34d399',
    fontSize: 13,
    fontWeight: '600',
  },
  progressRing: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 10,
    borderColor: '#34d399',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1f2937',
  },
  progressPercent: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700',
  },
  progressLabel: {
    color: '#9ca3af',
    fontSize: 12,
  },
  cardsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  summaryCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 5,
    elevation: 2,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginBottom: 10,
  },
  cardLabel: {
    color: '#6b7280',
    fontSize: 13,
    marginBottom: 4,
  },
  cardValue: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '700',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  sectionLink: {
    color: '#4f46e5',
    fontSize: 13,
    fontWeight: '600',
  },
  projectPreviewCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 5,
    elevation: 2,
  },
  projectPreviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  projectPreviewTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  projectPreviewBadge: {
    color: '#16a34a',
    fontSize: 12,
    fontWeight: '600',
  },
  projectPreviewText: {
    color: '#6b7280',
    fontSize: 13,
    marginTop: 2,
  },
  transactionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
  },
  transactionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  transactionIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  incomeIcon: {
    backgroundColor: '#dcfce7',
  },
  expenseIcon: {
    backgroundColor: '#fee2e2',
  },
  transactionIconText: {
    fontSize: 16,
    fontWeight: '700',
  },
  transactionTitle: {
    color: '#111827',
    fontWeight: '600',
    fontSize: 14,
  },
  transactionSubtitle: {
    color: '#6b7280',
    fontSize: 12,
    marginTop: 2,
  },
  transactionAmount: {
    fontWeight: '700',
    fontSize: 14,
  },
  incomeText: {
    color: '#16a34a',
  },
  expenseText: {
    color: '#dc2626',
  },
  button: {
    marginTop: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#111827',
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4f46e5',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
  fabText: {
    color: '#fff',
    fontSize: 30,
    fontWeight: '300',
    lineHeight: 30,
  },
  // Bottom sheet / modal styles
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  sheetContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    minHeight: 240,
  },
  sheetWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  sheetHandle: {
    width: 40,
    height: 2,
    backgroundColor: '#e2e8f0',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 12,
  },
  sheetTopShimmer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 8,
    height: 6,
    overflow: 'hidden',
    zIndex: 5,
    
  },
  sheetTopShimmerBar: {
    width: 140,
    height: 6,
    borderRadius: 4,
    backgroundColor: '#a78bfa',
    opacity: 0.9,
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#edf2f7',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  segmentedContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#edf2f7',
    borderRadius: 8,
    marginBottom: 10,
    overflow: 'hidden',
    alignSelf: 'center',
    width: 180,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.12,
    shadowRadius: 8,
    backgroundColor: '#fff',
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  
  segmentText: {
    color: '#111827',
  },
  segmentTextActive: {
    color: '#fff',
  },
  

  modalAddButton: {
    backgroundColor: '#4f46e5',
    paddingHorizontal: 25,
    paddingVertical: 8,
    borderRadius: 8,
    alignSelf: 'center',
    marginTop: 12,
  },
  modalAddButtonText: {
    color: '#fff',
  },
});
export default styles;